name: Locations
version: '0.1.1'
main: com.roseworld.Locations
api-version: '1.21'
authors: [ TMG-8047KG ]
description: Gives you an option to save locations
dependencies:
  bootstrap:
    RoseKingdom:
      required: true
      join-classpath: true
      load: BEFORE